//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BicycleWorldEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        public SalesOrder()
        {
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
        }
    
        public int SalesOrderID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}
